version: "3.9"

services:
  db:
    image: postgis/postgis:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    user: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: covidgeo123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    image: django
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    working_dir: /code/covidgeo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/code:Z"
      - "./data:/data:Z"
    restart: always
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - "db"


volumes:
  db_data: {}
